### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by nannal** [skzap/javalon#2]
````filestore/dabbott/dev/proje/node_modules/javalon/index.js:473
if (window) window.javalon = avalon
^

ReferenceError: window is not defined
    at Object.<anonymous> (/filestore/dabbott/dev/proje/node_modules/javalon/index.js:473:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/filestore/dabbott/dev/proje/testing.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
````

Commenting out like 473 solves the issue

**Comment by skzap** [comment]
fix in https://github.com/dtube/javalon/commit/c7b29bf94ca3b431e909ea1287df7d4802551d27
